services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes: 
            - ./redis.conf:/redis.conf
        command: ["redis-server", "/redis.conf"]

    fake_chat_watcher:
        image: fake-chat-watcher:latest
        depends_on:
            - redis
        command:
          python -u main.py
